/**
 * Explicit SQLite migration runner.
 *
 * Migrations are applied only when this module is called, never when a
 * connection is opened and never during a request. Each file runs in its own
 * transaction; the journal row is written in that same transaction so a failed
 * file is rolled back and never recorded as successful. A later run that finds
 * the same tag skips it only when the SHA-256 of the SQL file still matches
 * the committed hash; a changed file is a controlled error and applies nothing.
 */

import "server-only";

import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import type { SqliteConnection } from "./database";

/** Default folder generated by drizzle-kit. */
export const DEFAULT_MIGRATIONS_FOLDER = fileURLToPath(
  new URL("../../../db/migrations", import.meta.url),
);

/** Table that records migrations that finished successfully. */
export const SCHEMA_MIGRATION_TABLE = "schema_migration";

/** Reason why migrations could not be applied. */
export type MigrationErrorCode =
  | "journalMissing"
  | "invalidJournal"
  | "migrationFileMissing"
  | "migrationFailed"
  | "checksumMismatch";

/** Controlled failure while applying migrations. */
export interface MigrationError {
  readonly code: MigrationErrorCode;
  readonly tag?: string;
  readonly cause?: string;
}

/** Outcome of applying the migration folder. */
export type MigrationResult =
  | {
      readonly ok: true;
      readonly value: {
        readonly applied: readonly string[];
        readonly skipped: readonly string[];
      };
    }
  | { readonly ok: false; readonly error: MigrationError };

interface MigrationJournal {
  readonly entries: readonly { readonly tag: string }[];
}

/**
 * Applies pending SQL files from a drizzle-kit journal to a real SQLite file.
 */
export function applyMigrations(
  connection: SqliteConnection,
  migrationsFolder: string = DEFAULT_MIGRATIONS_FOLDER,
): MigrationResult {
  const journalPath = join(migrationsFolder, "meta/_journal.json");

  if (!existsSync(journalPath)) {
    return { ok: false, error: { code: "journalMissing" } };
  }

  const journal = readJournal(journalPath);

  if (!journal) {
    return { ok: false, error: { code: "invalidJournal" } };
  }

  ensureMigrationJournal(connection);

  const applied: string[] = [];
  const skipped: string[] = [];

  for (const entry of journal.entries) {
    const sqlPath = join(migrationsFolder, `${entry.tag}.sql`);

    if (!existsSync(sqlPath)) {
      return {
        ok: false,
        error: { code: "migrationFileMissing", tag: entry.tag },
      };
    }

    const sqlText = readFileSync(sqlPath, "utf8");
    const hash = createHash("sha256").update(sqlText).digest("hex");
    const existing = connection.sqlite
      .prepare(`SELECT hash FROM ${SCHEMA_MIGRATION_TABLE} WHERE tag = ?`)
      .get(entry.tag) as { hash: string } | undefined;

    if (existing) {
      if (existing.hash !== hash) {
        return {
          ok: false,
          error: { code: "checksumMismatch", tag: entry.tag },
        };
      }

      skipped.push(entry.tag);
      continue;
    }

    try {
      applyMigrationFile(connection, entry.tag, hash, sqlText);
      applied.push(entry.tag);
    } catch (cause) {
      return {
        ok: false,
        error: {
          code: "migrationFailed",
          tag: entry.tag,
          cause: cause instanceof Error ? cause.message : String(cause),
        },
      };
    }
  }

  return { ok: true, value: { applied, skipped } };
}

function readJournal(journalPath: string): MigrationJournal | null {
  try {
    const parsed: unknown = JSON.parse(readFileSync(journalPath, "utf8"));

    if (
      typeof parsed !== "object" ||
      parsed === null ||
      !("entries" in parsed) ||
      !Array.isArray(parsed.entries)
    ) {
      return null;
    }

    const entries: { tag: string }[] = [];

    for (const entry of parsed.entries) {
      if (
        typeof entry !== "object" ||
        entry === null ||
        !("tag" in entry) ||
        typeof entry.tag !== "string" ||
        entry.tag.trim() === ""
      ) {
        return null;
      }

      entries.push({ tag: entry.tag });
    }

    return { entries };
  } catch {
    return null;
  }
}

function ensureMigrationJournal(connection: SqliteConnection): void {
  connection.sqlite.exec(`
    CREATE TABLE IF NOT EXISTS ${SCHEMA_MIGRATION_TABLE} (
      tag TEXT PRIMARY KEY NOT NULL,
      hash TEXT NOT NULL,
      applied_at INTEGER NOT NULL
    )
  `);
}

function applyMigrationFile(
  connection: SqliteConnection,
  tag: string,
  hash: string,
  sqlText: string,
): void {
  const apply = connection.sqlite.transaction(() => {
    for (const statement of sqlText.split("--> statement-breakpoint")) {
      const sql = statement.trim();

      if (sql !== "") {
        connection.sqlite.exec(sql);
      }
    }

    connection.sqlite
      .prepare(
        `INSERT INTO ${SCHEMA_MIGRATION_TABLE} (tag, hash, applied_at) VALUES (?, ?, ?)`,
      )
      .run(tag, hash, Date.now());
  });

  apply();
}
